### ISSUE TITLE
cannot start training from a pre-trained model

### ISSUE THREAD

**Issue by eschmidbauer** [NVIDIA/radtts#3]
i've downloaded the model provided for [RADTTS](https://drive.google.com/file/d/1Rb2VMUwQahGrnpFSlAhCPh7OpDN3xgOr/view?usp=sharing)
and im trying to use it to start training but i get the following error:

```bash
python train.py -c config.json -p train_config.ignore_layers=["speaker_embedding.weight"] train_config.checkpoint_path='models/radtts++ljs-dap.pt'

> got rank 0 and world size 1 ...
/debug
Using seed 1007
Applying spectral norm to text encoder LSTM
/root/radtts/common.py:391: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:1980.)
  W = torch.qr(torch.FloatTensor(c, c).normal_())[0]
Applying spectral norm to context encoder LSTM

Initializing RAdam optimizer
Traceback (most recent call last):
  File "/root/radtts/train.py", line 498, in <module>
    train(n_gpus, rank, **train_config)
  File "/root/radtts/train.py", line 357, in train
    model, optimizer, iteration = load_checkpoint(
  File "/root/radtts/train.py", line 181, in load_checkpoint
    iteration = checkpoint_dict['iteration']
KeyError: 'iteration'
```

**Comment by rafaelvalle** [comment]
nice catch! it's because checkpoint_path requires a checkpoint dictionary with an optimizer and iteration number, which we don't provide.
please use warmstart_checkpoint_path instead of checkpoint_path and let us know

**Comment by taalua** [comment]
Hi, thank you for the pretrained model.
What type of config.json I should use for training? _agap, _bgap, or _dap?
I got this error:
line 187, in load_data
    'emotion': d[3],

**Comment by rafaelvalle** [comment]
can you please pull and try again? the previous dataloader expected emotion and durations in the filelist. the current works if the filelist has only filename, text and speaker label.

Are you planning to train on new data?

**Comment by sjkoelle** [comment]
I too would be interested in seeing a sample config for warm starting.  I imagine there may be differences in the learning scheduling?

**Comment by sjkoelle** [comment]
I've had more success training from scratch and warm starting when not ignoring the speaker embedding.  Warm starting a multispeaker does not work for me.
